theme: jekyll-theme-minimal
title: GENUARY
description: GENUARY is an artificially generated month of time where we build code that makes beautiful things.
keywords: genuary,art,code,generative,creative,coding
